[package]
name = "one_collect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscalls = { version = "0.6.13", features = ["x86_64", "arm"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "event"
harness = false
