name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_debug:
    name: Build and Test (Debug)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'one_collect: Build'
      working-directory: one_collect
      run: cargo build --verbose
    - name: 'one_collect: Run tests'
      working-directory: one_collect
      run: cargo test --verbose
    - name: 'cli: Build'
      working-directory: cli
      run: cargo build --verbose
    - name: 'cli: Run tests'
      working-directory: cli
      run: cargo test --verbose
    - name: 'ruwind: Build'
      working-directory: ruwind
      run: cargo build --verbose
    - name: 'ruwind: Run tests'
      working-directory: ruwind
      run: cargo test --verbose

  build_release:
    name: Build and Test (Release)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'one_collect: Build'
      working-directory: one_collect
      run: cargo build --release --verbose
    - name: 'one_collect: Run tests'
      working-directory: one_collect
      run: cargo test --release --verbose
    - name: 'cli: Build'
      working-directory: cli
      run: cargo build --release --verbose
    - name: 'cli: Run tests'
      working-directory: cli
      run: cargo test --release --verbose
    - name: 'ruwind: Build'
      working-directory: ruwind
      run: cargo build --release --verbose
    - name: 'ruwind: Run tests'
      working-directory: ruwind
      run: cargo test --release --verbose

  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run benchmarks
      working-directory: one_collect
      run: cargo bench --verbose

  docker_console:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Docker tests
      working-directory: test/docker/console-logger
      run: ./run.sh