name: Docker Tests

permissions:
  contents: read

on:
  workflow_call:

jobs:
  docker-tests:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Run Docker tests
      working-directory: test/docker/perf_export
      run: ./run.sh
