name: Docker Tests

permissions:
  contents: read

on:
  workflow_call:

jobs:
  docker-tests:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Run Docker tests
      working-directory: test/docker/perf_export
      run: ./run.sh
